plugins {
    id 'com.android.application'
}

android {
    namespace 'com.photosolver.app'
    compileSdk 34

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId 'com.photosolver.app'
        minSdk 26
        targetSdk 34
        versionCode 2
        versionName '1.1'
        buildConfigField "String", "APP_LAN_URL", "\"${appLanUrl}\""
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
